### ISSUE TITLE
Does not apply on nginx 1.23.4+

### ISSUE THREAD

**Issue by jirutka** [myfreeer/nginx-build-msys2#12]
The ngx-files patches don’t apply on nginx 1.23.4 and newer.

**Comment by jirutka** [comment]
It seems that these patches are not needed anymore; see https://github.com/nginx/nginx/commits/master/src/os/win32.

**Comment by myfreeer** [comment]
This patches are skipped if nginx 1.23.4 or later detected, would close this if ci build passes.

Link: <https://ci.appveyor.com/project/myfreeer/nginx-build-msys2/builds/47090633>
