### ISSUE TITLE
Release patches for 1.19.7

### ISSUE THREAD

**Issue by jirutka** [myfreeer/nginx-build-msys2#4]
Can you please tag 1.19.7? I’ve tried to apply the patches on this version and it’s clean.

**Comment by myfreeer** [comment]
https://github.com/myfreeer/nginx-build-msys2/releases/tag/1.19.7

**Comment by jirutka** [comment]
Thanks!

FYI: I’m using your patches in https://github.com/jirutka/nginx-binaries.
